### ISSUE TITLE
Error when I try to use IBAN validation

### ISSUE THREAD

**Issue by davi9922** [orumad/laravel-spanish-validator#5]
When I try to use the IBAN validation in a form, Laravel drops me this error:

![imagen](https://user-images.githubusercontent.com/55253543/181231730-7d8676e6-5b46-416c-b6bd-d724c4700088.png)

I suppose there is something wrong with the autoload of the Classes. 

If someone can help me, I will appreciate.

**Comment by enricv** [comment]
Same problem.

**Comment by enricv** [comment]
Solved, 

you have to install globalcitizen/php-iban package: https://github.com/globalcitizen/php-iban

Then you have to create an alias at congif/app.php file:

    'aliases' => Facade::defaultAliases()->merge([
        // 'ExampleClass' => App\Example\ExampleClass::class,

        'IBAN' => \PHP_IBAN\IBAN::class
    ])->toArray(),

Don't forget clear config cache:

php artisan config:clear

**Comment by danielmrdev** [comment]
Fixed in v1.3.0
